import "./globals.css";
import { OverlaysProvider } from "@/lib/CMP/cmp.overlaysCtx";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body>
        <OverlaysProvider>{children}</OverlaysProvider>
      </body>
    </html>
  );
}
